### ISSUE TITLE
in dialog use error

### ISSUE THREAD

**Issue by qq2540040142** [icerockdev/moko-permissions#140]
The same permission request code works normally in a normal compose, but an exception occurs in a dialog.
code：
```
@Composable
fun PermissionsRequest(vararg permission: Permission,onPermissionGranted: (Boolean) -> Unit): PermissionsController {
    val factory: PermissionsControllerFactory = rememberPermissionsControllerFactory()
    val permissionsController: PermissionsController = remember(factory) { factory.createPermissionsController() }
    val coroutineScope: CoroutineScope = rememberCoroutineScope()
    BindEffect(permissionsController)
    LaunchedEffect(Unit){
        var isGranted = true
        coroutineScope.launch {
            permission.forEach {
                val r = permissionsController.isPermissionGranted(it)
                if (!r) isGranted = false
            }
            onPermissionGranted(isGranted)
        }
    }
    return permissionsController
}
```
```
@Composable
fun CustomCameraView(modifier: Modifier = Modifier) {
var permissionState by remember {
        mutableStateOf(false)
    }
    val scope = rememberCoroutineScope()
    val permissionsController = PermissionsRequest(Permission.CAMERA){
        permissionState = it
    }
    if (permissionState){
        //todo Any
    }else{
        Column(modifier = modifier.background(black40), horizontalAlignment = Alignment.CenterHorizontally, verticalArrangement = Arrangement.Center) {
            Text( text = "please open permission", color = white)
            Button(onClick = {
                scope.launch {
                    try {
                        permissionsController.providePermission(Permission.CAMERA)
                        permissionState = true
                    }catch(deniedAlways: DeniedAlwaysException) {
                        // todo 
                    } catch(denied: DeniedException) {
                        // todo 
                    }
                }
            }){
                Text(text = "申请相机权限")
            }
        }
    }
}
```
use in dialog:
```
@Composable
fun ScanAddMaterialDialog(onDismissRequest: () -> Unit) {
    AlertDialog(onDismissRequest = onDismissRequest,
        title = { Text(text = "扫描标签")},
        text = {
            CustomCameraView(modifier = Modifier.fillMaxSize())
        },
        confirmButton = {},
        dismissButton = {
            TextButton(onClick = onDismissRequest) {
                Text(text = "取消")
            }
        }, containerColor = white)
}
```
error:
```
java.lang.IllegalStateException: android.view.ContextThemeWrapper@47c2ad9 context is not instance of ComponentActivity
                                         	at dev.icerock.moko.permissions.compose.BindEffect_androidKt$BindEffect$1.invokeSuspend(BindEffect.android.kt:23)
                                         	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                         	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
                                         	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
                                         	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
                                         	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
                                         	at android.os.Handler.handleCallback(Handler.java:942)
                                         	at android.os.Handler.dispatchMessage(Handler.java:99)
                                         	at android.os.Looper.loopOnce(Looper.java:211)
                                         	at android.os.Looper.loop(Looper.java:300)
                                         	at android.app.ActivityThread.main(ActivityThread.java:8321)
                                         	at java.lang.reflect.Method.invoke(Native Method)
                                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:581)
                                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
                                         	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@c6d4aa, androidx.compose.runtime.BroadcastFrameClock@ef0889b, StandaloneCoroutine{Cancelling}@8eb9438, AndroidUiDispatcher@ec75c11]
```

**Comment by leo-beliakov** [comment]
[Alex009](https://github.com/Alex009), the same issue happens with androidx.compose.material3.ModalBottomSheet

**Comment by sigmadeltasoftware** [comment]
Experiencing the same issue within a `ModalBottomSheet` as mentioned above

**Comment by lemkoleg** [comment]
Has anyone dealt with this problem?

**Comment by dandehavilland** [comment]
You can try something like this to drill down to the `ComponentActivity`:

```kotlin
// CustomBindEffect.android.kt

@Composable
actual fun CustomBindEffect(controller: PermissionsController) {
    val lifecycleOwner: LifecycleOwner = LocalLifecycleOwner.current
    val context: Context = LocalContext.current

    LaunchedEffect(controller, lifecycleOwner, context) {
        val activity = checkNotNull(context.getActivity() as? ComponentActivity) {
            "$context context is not instance of ComponentActivity"
        }

        controller.bind(activity)
    }
}

private fun Context.getActivity(): Activity? {
    return when (this) {
        is Activity -> this
        is ContextWrapper -> this.baseContext.getActivity()
        else -> null
    }
}

```
