### ISSUE TITLE
Fatal Exception: java.util.NoSuchElementException Array is empty.

### ISSUE THREAD

**Issue by krottv** [icerockdev/moko-permissions#47]
Some users of my app experience the crash with the latest moko permissions - 0.10.1

```
Fatal Exception: java.util.NoSuchElementException: Array is empty.
       at kotlin.collections.ArraysKt___ArraysKt.first(ArraysKt___ArraysKt.java:1013)
       at dev.icerock.moko.permissions.ResolverFragment.onRequestPermissionsResult(ResolverFragment.java:54)
       at androidx.fragment.app.FragmentManager$11.onActivityResult(FragmentManager.java:2967)
       at androidx.fragment.app.FragmentManager$11.onActivityResult(FragmentManager.java:2939)
       at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:392)
       at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:351)
       at androidx.activity.ComponentActivity.onRequestPermissionsResult(ComponentActivity.java:658)
       at androidx.fragment.app.FragmentActivity.onRequestPermissionsResult(FragmentActivity.java:636)
       at android.app.Activity.requestPermissions(Activity.java:5278)
       at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:516)
       at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:190)
       at androidx.activity.result.ActivityResultRegistry$3.launch(ActivityResultRegistry.java:226)
       at dev.icerock.moko.permissions.PermissionsControllerImpl.providePermission(PermissionsControllerImpl.java:47)
       at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
       at androidx.fragment.app.FragmentManager.launchRequestPermissions(FragmentManager.java:3044)
       at androidx.fragment.app.Fragment.requestPermissions(Fragment.java:1561)
       at dev.icerock.moko.permissions.ResolverFragment.requestPermission(ResolverFragment.java:36)
       at dev.icerock.moko.permissions.PermissionsControllerImpl.providePermission(PermissionsControllerImpl.java:60)
       at app.inspiry.edit.EditActivity$pickNewImage$1.invokeSuspend(EditActivity.java:1249)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuationKt.java:367)
       at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(CancellableKt.java:30)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.startCoroutineImpl(BuildersKt__Builders_commonKt.java:192)
       at kotlinx.coroutines.BuildersKt.startCoroutineImpl(BuildersKt.java:1)
       at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.java:134)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(BuildersKt__Builders_commonKt.java:56)
       at kotlinx.coroutines.BuildersKt.launch(BuildersKt.java:1)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(BuildersKt__Builders_commonKt.java:47)
       at kotlinx.coroutines.BuildersKt.launch$default(BuildersKt.java:1)
       at app.inspiry.edit.EditActivity.pickNewImage(EditActivity.java:1247)
       at app.inspiry.views.media.InnerMediaViewAndroid.setPickImage$lambda-2(InnerMediaViewAndroid.java:182)
       at app.inspiry.views.media.InnerMediaViewAndroid$$InternalSyntheticLambda$0$3c79bbfbf7f8a6c4d25cb6ad0b8c5c8e0a90bdf875c794783a7a740bccad53f6$0.onClick$bridge(InnerMediaViewAndroid.java:9)
       at android.view.View.performClick(View.java:8160)
       at android.view.View.performClickInternal(View.java:8137)
       at android.view.View.access$3700(View.java:888)
       at android.view.View$PerformClick.run(View.java:30236)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8512)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
```

**Comment by Alex009** [comment]
from android documentation - https://developer.android.com/reference/android/app/Activity.html#onRequestPermissionsResult(int,%20java.lang.String[],%20int[])

> Note: It is possible that the permissions request interaction with the user is interrupted. In this case you will receive empty permissions and results arrays which should be treated as a cancellation.

so we should fix this case
