### ISSUE TITLE
Android OS12 BLUETOOTH_CONNECT error

### ISSUE THREAD

**Issue by ToysoftInc** [icerockdev/moko-permissions#52]
Does this library support Android OS12?

Getting security crash about android.permission.BLUETOOTH_CONNECT 

I'm using the below 2 permissions and the app is crashing,

 LOCATION,
 BLUETOOTH_LE,

**Comment by Alex009** [comment]
Please add crash log

**Comment by ToysoftInc** [comment]
022-04-20 19:37:26.771 11214-12819/com.skf.imx1.android E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-6
    Process: com.test.android, PID: 11214
    java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for AttributionSource { uid = 10569, packageName = com.test.android, attributionTag = null, token = android.os.BinderProxy@b49c0e3, next = null }: AdapterService getRemoteName
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
        at android.os.Parcel.createException(Parcel.java:2421)
        at android.os.Parcel.readException(Parcel.java:2404)
        at android.os.Parcel.readException(Parcel.java:2346)
        at android.bluetooth.IBluetooth$Stub$Proxy.getRemoteName(IBluetooth.java:5470)

**Comment by Alex009** [comment]
Here https://github.com/icerockdev/moko-permissions/blob/master/permissions/src/androidMain/kotlin/dev/icerock/moko/permissions/PermissionsControllerImpl.kt you can see that now not supported BLUETOOTH_CONNECT. It should be added to support list

**Comment by ToysoftInc** [comment]
can you push a new version?
