### ISSUE TITLE
Error using androidx.activity.ComponentActivity

### ISSUE THREAD

**Issue by n1rocket** [icerockdev/moko-permissions#97]
My activity extend of androidx.activity.ComponentActivity.

is there any option to workaround?

`java.lang.ClassCastException: com.company.component.ui.SActivity cannot be cast to androidx.fragment.app.FragmentActivity
	at dev.icerock.moko.permissions.compose.BindEffect_androidKt$BindEffect$1.invokeSuspend(BindEffect.android.kt:24)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:68)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
	at android.view.Choreographer.doCallbacks(Choreographer.java:793)
	at android.view.Choreographer.doFrame(Choreographer.java:724)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:954)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7551)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@c4c4f7, androidx.compose.runtime.BroadcastFrameClock@5d54f64, StandaloneCoroutine{Cancelling}@55b75cd, AndroidUiDispatcher@f63ce82]
`

thanks!

**Comment by mcmendesuol** [comment]
I am, with moko-media and moko-permission accurency this error

**Comment by omarzer0** [comment]
@n1rocket @mcmendesuol 
You can just change what your MainActivity extends => Change ComponentActivity to FragmentActivity

**Comment by maeceloacm1998** [comment]
<img width="1010" alt="image" src="https://github.com/icerockdev/moko-permissions/assets/75353400/a61c92e6-2ac1-458c-8452-4052e11a69c7">
when using your soluction @omarzer0, showing the this error

**Comment by omarzer0** [comment]
@maeceloacm1998 
Could you please show the code?
